GET http://10.0.2.2:3000/inscriptions
Accept: application/json

###

GET http://10.0.2.2:3000/inscriptions?classe=L1 MAE
Accept: application/json
###

GET http://10.0.2.2:3000/inscriptions?classe=L3 MIAGE
Accept: application/json
###

GET http://10.0.2.2:3000/inscriptions?classe=L2 INFO
Accept: application/json